TOOL_NAME    := daq
XDP_TARGETS  := daq.bpf
USER_TARGETS := daq
TEST_FILE    := 

LIB_DIR       = $(abspath ../xdp-tools/lib)
USER_LIBS     = 
MAN_PAGE     := 

CFLAGS += -g -std=gnu11
LDFLAGS += -lpthread

include $(LIB_DIR)/common.mk
